//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFormsLeaflet.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Miasta
    {
        public System.Guid Oid { get; set; }
        public string Miasto { get; set; }
        public decimal Latitude { get; set; }
        public decimal Longitude { get; set; }
        public string Ikona { get; set; }
    }
}
